import Foundation

/// Installs and removes AgentDeck's lifecycle hooks in Claude Code and Codex CLI.
///
/// Both CLIs are configured to invoke a small generated forwarder script on each
/// lifecycle event. The script reads the hook's stdin JSON, merges in `tool`,
/// `event`, and the pane's controlling `tty`, and POSTs the result to our local
/// listener (`127.0.0.1:<port>/event`) matching the `HookEvent` wire contract in
/// Model.swift.
///
/// Config files are always merged (never clobbered): existing hook entries from
/// other tools/plugins are preserved, and our own entries are only added once
/// (matched by exact command string), making install idempotent.
enum HookInstaller {
    struct Status { var claude: Bool; var codex: Bool }

    // MARK: - Paths

    private static var homeDirectory: URL {
        FileManager.default.homeDirectoryForCurrentUser
    }

    private static var claudeSettingsURL: URL {
        homeDirectory.appendingPathComponent(".claude/settings.json")
    }

    private static var claudeBackupURL: URL {
        homeDirectory.appendingPathComponent(".claude/settings.json.agentdeck.bak")
    }

    private static var codexHooksURL: URL {
        homeDirectory.appendingPathComponent(".codex/hooks.json")
    }

    private static var forwarderScriptURL: URL {
        AgentDeck.supportDir.appendingPathComponent("forward-event.sh")
    }

    private static var mergerScriptURL: URL {
        AgentDeck.supportDir.appendingPathComponent("merge-event.py")
    }

    /// Events wired into Claude Code's `~/.claude/settings.json`.
    private static let claudeEvents = [
        "SessionStart", "UserPromptSubmit", "PreToolUse", "Notification",
        "Stop", "SubagentStop", "SessionEnd",
    ]

    /// Events wired into Codex CLI's `~/.codex/hooks.json`.
    ///
    /// Verified against the current Codex hooks schema (developers.openai.com/codex/config-reference,
    /// learn.chatgpt.com/docs/hooks): hooks live under a top-level `"hooks"` object keyed by event
    /// name, each mapping to an array of matcher-groups `{ "matcher": ..., "hooks": [ { "type":
    /// "command", "command": ... } ] }` — structurally the same shape Claude Code uses. Codex hooks
    /// receive one JSON object on stdin (fields include session_id, cwd, hook_event_name, model,
    /// permission_mode), so no `notify`-style argv fallback is needed. `hooks.json` is a fully
    /// documented, first-class config surface (alongside inline `config.toml [hooks]` tables), so we
    /// write there rather than touching TOML.
    private static let codexEvents = [
        "SessionStart", "UserPromptSubmit", "PreToolUse", "PermissionRequest", "Stop",
    ]

    private static func command(for tool: String, event: String) -> String {
        // The forwarder lives under "Application Support" — a path WITH A SPACE.
        // The command is run through a shell, so the path MUST be quoted or the
        // shell splits it (…/Library/Application → "command not found").
        "'\(forwarderScriptURL.path)' \(tool) \(event)"
    }

    // MARK: - status()

    static func status() -> Status {
        let scriptPath = forwarderScriptURL.path
        let claudeText = (try? String(contentsOf: claudeSettingsURL, encoding: .utf8)) ?? ""
        let codexText = (try? String(contentsOf: codexHooksURL, encoding: .utf8)) ?? ""
        return Status(
            claude: claudeText.contains(scriptPath),
            codex: codexText.contains(scriptPath)
        )
    }

    // MARK: - install(port:)

    static func install(port: UInt16) throws {
        try FileManager.default.createDirectory(at: AgentDeck.supportDir, withIntermediateDirectories: true)
        try writeForwarderScript(port: port)
        try writeMergerScript()
        try installClaudeHooks()
        try installCodexHooks()
    }

    // MARK: - uninstall()

    static func uninstall() throws {
        try uninstallClaudeHooks()
        try uninstallCodexHooks()

        let fm = FileManager.default
        try? fm.removeItem(at: forwarderScriptURL)
        try? fm.removeItem(at: mergerScriptURL)
    }

    // MARK: - Generated scripts

    private static func writeForwarderScript(port: UInt16) throws {
        let supportPath = AgentDeck.supportDir.path
        let script = """
        #!/bin/bash
        # AgentDeck event forwarder. Generated by HookInstaller — do not edit by hand.
        # Invoked by CLI hooks as: forward-event.sh <tool> <event>
        # Reads the hook's stdin JSON, merges in tool/event/tty, POSTs it to the
        # local AgentDeck listener. Always exits 0 and never blocks the CLI.
        TOOL="$1"
        EVENT="$2"
        PORT="\(port)"
        SUPPORT_DIR="\(supportPath)"

        # Find the controlling tty of the CLI pane. The hook subprocess itself has
        # NO controlling terminal, so walk up the parent chain until we find one —
        # the CLI process (node/codex) running in the pane holds the pane's tty.
        tty=""
        pid=$$
        while [ -n "$pid" ] && [ "$pid" -gt 1 ]; do
          t=$(ps -o tty= -p "$pid" 2>/dev/null | tr -d ' ')
          if [ -n "$t" ] && [ "$t" != "??" ]; then
            tty="/dev/$t"
            break
          fi
          pid=$(ps -o ppid= -p "$pid" 2>/dev/null | tr -d ' ')
        done

        stdin_json="$(cat)"

        json="$(printf '%s' "$stdin_json" | /usr/bin/python3 "$SUPPORT_DIR/merge-event.py" "$TOOL" "$EVENT" "$tty" 2>/dev/null)"

        if [ -n "$json" ]; then
          curl -s -m 2 -X POST -H 'Content-Type: application/json' -d "$json" "http://127.0.0.1:$PORT/event" >/dev/null 2>&1
        fi

        exit 0
        """
        try script.write(to: forwarderScriptURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: forwarderScriptURL.path)
    }

    private static func writeMergerScript() throws {
        let script = """
        #!/usr/bin/env python3
        # AgentDeck event merger. Generated by HookInstaller — do not edit by hand.
        # Reads the hook's stdin JSON, overlays tool/event/tty, prints merged JSON.
        import json
        import sys


        def main() -> None:
            tool = sys.argv[1] if len(sys.argv) > 1 else ""
            event = sys.argv[2] if len(sys.argv) > 2 else ""
            tty = sys.argv[3] if len(sys.argv) > 3 else ""

            raw = sys.stdin.read()
            data = {}
            try:
                parsed = json.loads(raw) if raw.strip() else {}
                if isinstance(parsed, dict):
                    data = parsed
            except Exception:
                data = {}

            data["tool"] = tool
            data["event"] = event
            if tty:
                data["tty"] = tty

            print(json.dumps(data))


        if __name__ == "__main__":
            main()
        """
        try script.write(to: mergerScriptURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: mergerScriptURL.path)
    }

    // MARK: - Claude Code (~/.claude/settings.json)

    private static func installClaudeHooks() throws {
        let fm = FileManager.default
        var root: [String: Any] = [:]
        if let data = try? Data(contentsOf: claudeSettingsURL) {
            // Back up the ORIGINAL settings exactly once. install() runs on every
            // launch, so overwriting an existing backup would clobber the pristine
            // pre-AgentDeck copy with an already-hook-modified one.
            if !fm.fileExists(atPath: claudeBackupURL.path) {
                try? data.write(to: claudeBackupURL)
            }
            if let parsed = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
                root = parsed
            }
        }

        var hooks = root["hooks"] as? [String: Any] ?? [:]
        for event in claudeEvents {
            hooks[event] = upsertGroups(hooks[event], command: command(for: "claude", event: event))
        }
        root["hooks"] = hooks

        try fm.createDirectory(at: claudeSettingsURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        let data = try JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys])
        try data.write(to: claudeSettingsURL, options: .atomic)
    }

    private static func uninstallClaudeHooks() throws {
        guard let data = try? Data(contentsOf: claudeSettingsURL),
              var root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              var hooks = root["hooks"] as? [String: Any]
        else { return }

        for event in claudeEvents {
            hooks[event] = prunedGroups(hooks[event], removing: command(for: "claude", event: event))
        }
        root["hooks"] = hooks.isEmpty ? nil : hooks

        let out = try JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys])
        try out.write(to: claudeSettingsURL, options: .atomic)
    }

    // MARK: - Codex CLI (~/.codex/hooks.json)

    private static func installCodexHooks() throws {
        let fm = FileManager.default
        var root: [String: Any] = [:]
        if let data = try? Data(contentsOf: codexHooksURL),
           let parsed = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            root = parsed
        }

        var hooks = root["hooks"] as? [String: Any] ?? [:]
        for event in codexEvents {
            hooks[event] = upsertGroups(hooks[event], command: command(for: "codex", event: event), matcher: ".*")
        }
        root["hooks"] = hooks
        if root["description"] == nil {
            root["description"] = "AgentDeck lifecycle hooks — forwards session events to the AgentDeck overlay."
        }

        try fm.createDirectory(at: codexHooksURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        let data = try JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys])
        try data.write(to: codexHooksURL, options: .atomic)
    }

    private static func uninstallCodexHooks() throws {
        guard let data = try? Data(contentsOf: codexHooksURL),
              var root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              var hooks = root["hooks"] as? [String: Any]
        else { return }

        for event in codexEvents {
            hooks[event] = prunedGroups(hooks[event], removing: command(for: "codex", event: event))
        }
        root["hooks"] = hooks.isEmpty ? nil : hooks

        let out = try JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys])
        try out.write(to: codexHooksURL, options: .atomic)
    }

    // MARK: - Shared matcher-group merge/prune helpers
    //
    // Both Claude Code and Codex CLI use the same hook shape for a given event:
    // an array of matcher-groups, each `{ "matcher": <string>, "hooks": [ { "type":
    // "command", "command": <string> } ] }`. These helpers add/remove our own
    // command idempotently while leaving any other tool's entries untouched.

    /// Returns `existing` (an `Any?` expected to be `[[String: Any]]`) with a group
    /// added for `command`, unless a group already contains that exact command.
    private static func mergedGroups(_ existing: Any?, adding command: String, matcher: String = "") -> [[String: Any]] {
        var groups = existing as? [[String: Any]] ?? []
        let alreadyPresent = groups.contains { group in
            let entries = group["hooks"] as? [[String: Any]] ?? []
            return entries.contains { ($0["command"] as? String) == command }
        }
        if !alreadyPresent {
            let entry: [String: Any] = ["type": "command", "command": command]
            groups.append(["matcher": matcher, "hooks": [entry]])
        }
        return groups
    }

    /// Self-healing add: removes ANY prior entry that references our forwarder
    /// script path (catching stale/broken variants — e.g. the old unquoted command
    /// that the shell mis-split), then appends the one correct `command`. Foreign
    /// hooks (whose command doesn't contain our script path) are left untouched.
    private static func upsertGroups(_ existing: Any?, command: String, matcher: String = "") -> [[String: Any]] {
        let scriptPath = forwarderScriptURL.path
        var groups = (existing as? [[String: Any]] ?? []).compactMap { group -> [String: Any]? in
            guard var entries = group["hooks"] as? [[String: Any]] else { return group }
            entries.removeAll { ($0["command"] as? String)?.contains(scriptPath) == true }
            if entries.isEmpty { return nil }   // was only ours → drop the empty group
            var g = group
            g["hooks"] = entries
            return g
        }
        groups.append(["matcher": matcher, "hooks": [["type": "command", "command": command]]])
        return groups
    }

    /// Returns `existing` with any hook entry matching `command` removed, dropping
    /// matcher-groups that become empty as a result.
    private static func prunedGroups(_ existing: Any?, removing command: String) -> [[String: Any]] {
        let groups = existing as? [[String: Any]] ?? []
        return groups.compactMap { group -> [String: Any]? in
            guard var entries = group["hooks"] as? [[String: Any]] else { return group }
            entries.removeAll { ($0["command"] as? String) == command }
            guard !entries.isEmpty else { return nil }
            var pruned = group
            pruned["hooks"] = entries
            return pruned
        }
    }
}
